image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  key:
    files:
      - Cargo.lock
  paths:
    - cargo/
    - target/

test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test

pages:
  stage: deploy
  cache:
    key:
      files:
        - Cargo.lock
    paths:
      - cargo/
      - target/
    policy: pull
  script:
    - cargo doc --no-deps
    - mv target/doc public
  artifacts:
    paths:
      - public
  only:
    - main
