image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  key:
    files:
      - Cargo.lock
  paths:
    - cargo/
    - vendor/

test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

pages:
  stage: deploy
  script:
    - cargo doc --release --no-deps
  artifacts:
    paths:
      - target/doc
  only:
    - main
